### PR TITLE
Initial release

### LINKED ISSUE #2: please link proper repo / remove this one
hey there, i was looking for this module and ended up in this empty repo. Can you please link to this right one? https://github.com/finom/last-release-git

### PR DESCRIPTION
**Pull request by pvdlg**
Will allow to use `semantic-release` without `npm` once semantic-release/semantic-release#515 is merged.

- Unshallow repo
- Retrieve highest version form tags

@gr2m can you enable Travis, Codecov, Greenkeeper for the repo and add GH_TOKEN and NPM_TOKEN to Travis ?
Can you also setup the master branch to be protected (I don't have admin right on this repo)? 
Thanks

Fix #1, Fix #2

### CODE REVIEW

**Comment by gr2m** [comment]
I’ve setup everything, currently waiting for codecov.io 
[image](https://codecov.io/gh/semantic-release/last-release-git-tag/settings)

**Comment by gr2m** [comment]
well it show the same on all other repositories. I don’t get coveralls, always having problems activating it :( I guess we can just merge it in

**Comment by pvdlg** [comment]
> well it show the same on all other repositories. I don’t get coveralls, always having problems activating it :( I guess we can just merge it in

It seems to be a problem until we merge the first PR. Looking at the Codecov admin everything seems ok now.

**Comment by gr2m** [comment]
you are right! I checked e.g. https://codecov.io/gh/semantic-release/release-notes-generator/settings where it still shows the message that it hasn’t been yet activated. I also checked https://codecov.io/gh/semantic-release/semantic-release/settings and https://codecov.io/gh/semantic-release/npm/settings

**Pull request merged**
